zeebe-cluster-helm:
  image:
    repository: camunda/zeebe
    tag: 1.2.0
    pullPolicy: IfNotPresent

  # ZEEBE CFG
  clusterSize: 2
  partitionCount: 6
  replicationFactor: 3
  cpuThreadCount: 4
  ioThreadCount: 4
  gatewayMetrics: true

  podSecurityContext:
    capabilities:
          add: ["NET_ADMIN"]

  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_LOG_APPENDER
        value: Stackdriver
      - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
        value: zeebe-gateway
      - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: ATOMIX_LOG_LEVEL
        value: INFO
      - name: ZEEBE_LOG_LEVEL
        value: DEBUG
      - name: ZEEBE_GATEWAY_MONITORING_ENABLED
        value: "true"
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "14"
    resources:
      limits:
        cpu: 4
        memory: 32Gi
      requests:
        cpu: 4
        memory: 16Gi

  # Uncomment to add custom YAML configuration
  # This will overwrite anything at the application.yml location
  # zeebeCfg: {}

  # JavaOpts:
  # DEFAULTS
  JavaOpts: >-
    -XX:MaxRAMPercentage=25.0
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/zeebe/data
    -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
    -Xlog:gc*:file=/usr/local/zeebe/data/gc.log:time:filecount=7,filesize=8M

  # Environment variables
  env:
    # Enable JSON logging for google cloud stackdriver
    - name: ZEEBE_LOG_APPENDER
      value: Stackdriver
    - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      value: zeebe-broker
    - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    # Avoid tons of noise when exporting larger payloads
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ATOMIX_LOG_LEVEL
      value: INFO
    - name: ZEEBE_LOG_LEVEL
      value: DEBUG
    - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
      value: "0.8"
    - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
      value: "0.9"
    - name: ZEEBE_BROKER_EXPERIMENTAL_ENABLEPRIORITYELECTION
      value: "true"
    - name: ZEEBE_BROKER_EXPERIMENTAL_DISABLEEXPLICITRAFTFLUSH
      value: "true"

  # RESOURCES
  resources:
    limits:
      cpu: 14
      memory: 54Gi
    requests:
      cpu: 14
      memory: 32Gi

  # PVC
  pvcAccessMode: ["ReadWriteOnce"]
  pvcSize: 512Gi
  pvcStorageClassName: ssd


  # ELASTIC
  elasticsearch:
    enabled: true
    imageTag: 7.13.2

    replicas: 3
    minimumMasterNodes: 2

    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ssd"
      resources:
        requests:
          storage: 512Gi

    esJavaOpts: "-Xmx32g -Xms32g"

    resources:
      requests:
        cpu: 14
        memory: 32Gi
      limits:
        cpu: 14
        memory: 54Gi

  # KIBANA
  kibana:
    enabled: false

  # PROMETHEUS
  prometheus:
    enabled: false

    servicemonitor:
      enabled: true

zeebe-operate-helm:
  image:
    repository: camunda/operate
    tag: 1.2.0-alpha2
  resources:
    requests:
      cpu: 14
      memory: 32Gi
    limits:
      cpu: 14
      memory: 54Gi
  env:
  - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_BATCHSIZE
    value: "400"
  - name: CAMUNDA_OPERATE_IMPORTER_THREADSCOUNT
    value: "14"